---
# tasks file for ansible-role-configure-sshd
---
- name: Configure sshd for EL hosts
  become: true
  when:
    - ansible_facts['os_family'] == "RedHat"
  block:
    - name: Insure sshd is installed and running on the hosts
      ansible.builtin.dnf:
        name: 
          - openssh-server
        state: latest
    
    - name: Copy production sshd_config to host
      ansible.builtin.copy:
        src: "templates/el8_sshd.conf.j2"
        dest: "/etc/ssh/sshd_config"
        mode: '0600'
        owner: root
        group: root
        setype: "etc_t"
        backup: true
      register: sshd_copy
      notify: Restart sshd
    
    - name: Configure issue banner for host
      ansible.builtin.copy:
        src: "templates/issue.j2"
        dest: "/etc/issue"
        mode: '0644'
        owner: root
        group: root
        setype: "etc_t"
        backup: true
      register: issue_copy

    - name: Configure issue.net banner for host
      ansible.builtin.copy:
        src: "templates/issue.net.j2"
        dest: "/etc/issue.net"
        mode: '0644'
        owner: root
        group: root
        setype: "etc_t"
        backup: true
      register: issuenet_copy