---
# handlers file for ansible-role-configure-sshd
- name: Restart sshd
  become: true
  async: 5
  poll: 1
  when:
    - ansible_facts['os_family'] == "RedHat"
  ansible.builtin.systemd_service:
    name: sshd.service
    state: reloaded